### ISSUE TITLE
Scan strucked in this stage 

### ISSUE THREAD

**Issue by ChathurangaBW** [haroonawanofficial/XSSInspector-SecurityToolkit-AI-ML#3]
Is there any way to resolve this issue? 
![image](https://github.com/user-attachments/assets/d6d9196d-551a-4ba4-8e5f-477bafcf9895)

**Comment by haroonawanofficial** [comment]
This is not stuck. The script uses multiprocessing and fully utilizes your
CPU cores. Let it cool down a bit, wait for all processes to finish, and
ensure you have write permissions for the report. If you're using Linux,
make sure you have given the proper permissions.

Give it 20 minutes to finish the processes, after which it will generate a
model, structure, and trained PKL file that you can use later. If you do
not want the model to be trained, simply run the script without the "use
model" option, and you can still view the report.

It's all good. You can then view your trained model's accuracy by using
"evaluate model."

Hope this helps you a lot.

**Comment by j0hnZ3RA** [comment]
Mine for some reason never saves the report, I've run it several times, and I can't get the result.

![image](https://github.com/user-attachments/assets/9f02e0af-e837-4a4c-a9f9-a980f8da2528)

![image](https://github.com/user-attachments/assets/697a16cb-562c-4162-9c39-303a64c123b0)

**Comment by haroonawanofficial** [comment]
we need to check permission, do this; sudo chmod -R 777 /home/havoc/report1.html and run again, if it works great, otherwise we need to check and make this automated fix in the code, let me know after testing

**Comment by haroonawanofficial** [comment]
Fixed in update, it should work
