### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Ninjaex13** [haroonawanofficial/XSSInspector-SecurityToolkit-AI-ML#6]
Hi there! I'm getting the "Illegal instruction (core dumped)" error after doing all the instructions, from what I've read it could be cause by the cpu which is I5-6500T. Am I right, is the cpu the problem making it incompatible?
![Screenshot_1](https://github.com/user-attachments/assets/d17605d1-bfa8-4f4c-8c83-ac2a5810b91d)

**Comment by haroonawanofficial** [comment]
This is related to your incompatible installations. For example, you have TensorFlow 2.13.1, which requires version 1.24.3, but you have 1.24.4, which is incompatible. Please create a virtual environment and then try running the script; it should work.

**Comment by Ninjaex13** [comment]
Excuse me but I'm trying to run it on a laptop without external GPU and I'm
wondering if it's even possible because I'm getting
[INFO] Starting the XSS Scanner at 2024-12-04 17:57:47.
2024-12-04 17:57:47.453294: E
external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call
to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

На пн, 25.11.2024 г. в 10:25 Haroon Ahmad Awan ***@***.***>
написа:
